<a href="https://colab.research.google.com/github/jcharly797/Archivos-/blob/main/Iris_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Data


In [ ]:
#!pip install tensorflow

In [1]:
# first neural network with keras tutorial

from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#
import warnings
warnings.filterwarnings('ignore')

In [3]:
#
dataset = loadtxt('https://raw.githubusercontent.com/jcharly797/Archivos-/main/iris.csv', delimiter=',')

dataset

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3

In [20]:
# split into input (X) and output (y) variables
X = dataset[:,0:4]
y = dataset[:,4]

In [21]:
#
model = Sequential()

model.add(Dense(12, input_shape = (4,), activation = 'relu'))

model.add(Dense(8, activation = 'relu'))

model.add(Dense(1, activation = 'sigmoid'))

In [22]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [23]:
# fit the keras model on the dataset
model.fit(X, y, epochs=100, batch_size=5)

Epoch 1/100
30/30 [==============================] - 1s 4ms/step - loss: -0.9630 - accuracy: 0.3333
Epoch 2/100
30/30 [==============================] - 0s 4ms/step - loss: -2.6150 - accuracy: 0.3333
Epoch 3/100
30/30 [==============================] - 0s 3ms/step - loss: -4.8775 - accuracy: 0.3333
Epoch 4/100
30/30 [==============================] - 0s 3ms/step - loss: -8.2735 - accuracy: 0.3333
Epoch 5/100
30/30 [==============================] - 0s 4ms/step - loss: -12.8430 - accuracy: 0.3333
Epoch 6/100
30/30 [==============================] - 0s 4ms/step - loss: -18.9086 - accuracy: 0.3333
Epoch 7/100
30/30 [==============================] - 0s 5ms/step - loss: -26.9329 - accuracy: 0.3333
Epoch 8/100
30/30 [==============================] - 0s 3ms/step - loss: -36.9695 - accuracy: 0.3333
Epoch 9/100
30/30 [==============================] - 0s 5ms/step - loss: -49.6794 - accuracy: 0.3333
Epoch 10/100
30/30 [==============================] - 0s 5ms/step - loss: -65.1230 - accuracy: 

In [24]:
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

5/5 [==============================] - 0s 3ms/step - loss: -31684.0273 - accuracy: 0.3333
Accuracy: 33.33


## Make Predictions

In [25]:
# make probability predictions with the model
predictions = model.predict(X)

predictions[:10]

5/5 [==============================] - 0s 3ms/step


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [26]:
# round predictions
rounded = [round(x[0]) for x in predictions]

rounded[:10]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [27]:
# Alternately, you can convert the probability into 0 or 1 to predict crisp classes directly; for example:

# make class predictions with the model
predictions = (model.predict(X) > 0.5).astype(int)

predictions[:10]

5/5 [==============================] - 0s 3ms/step


array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])