<a href="https://colab.research.google.com/github/jcharly797/Archivos-/blob/main/Tarea_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INTRODUCCIÓN A DEEP LEARNING

## ¿Qué es el aprendizaje profundo?

* Algunos de los avances más impresionantes en inteligencia artificial de los últimos años se han producido en el campo del aprendizaje profundo.

* El procesamiento del lenguaje natural, el reconocimiento de imágenes y los juegos son tareas en las que los modelos de aprendizaje profundo se han acercado o incluso superado el rendimiento a nivel humano.

* ¿Qué es el aprendizaje profundo? El aprendizaje profundo es un enfoque del aprendizaje automático que ha permitido identificar tipos de patrones complejos y jerárquicos que se encuentran en los conjuntos de datos más desafiantes del mundo real.

El objetivo principal es presentar un proyecto sencillo de Deep Learning y practicar los principales usos de bibliotecas como `keras` o `tensorflow`.

# Load Data


In [ ]:
#!pip install tensorflow

In [1]:
# first neural network with keras tutorial

from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#
import warnings
warnings.filterwarnings('ignore')

En esta clase de Keras, utilizaremos el conjunto de datos sobre el inicio de la diabetes de la población originaria Pima.

Este es un conjunto de datos de aprendizaje automático estándar del repositorio [UCI Machine Learning](https://archive.ics.uci.edu/). Los datos consisten en los registros médicos de los indios Pima.

Como tal, se trata de un problema de clasificación binaria (inicio de diabetes como 1 o no como 0).

Todas las variables de entrada que describen a cada paciente son numéricas--esto facilita su uso directamente con redes neuronales que esperan valores numéricos de entrada y salida y es una opción ideal para nuestra primera red neuronal en Keras--.

El conjunto de datos está disponible [aquí](https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv). Es un archivo CSV del conjunto de datos (pima-indians-diabetes.csv). Los detalles del conjunto de datos esta disponible [aquí](https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.names).

The variables can be summarized as follows:

Input Variables (X):

* Number of times pregnant
* Plasma glucose concentration at 2 hours in an oral glucose tolerance test
* Diastolic blood pressure (mm Hg)
* Triceps skin fold thickness (mm)
* 2-hour serum insulin (mu U/ml)
* Body mass index (weight in kg/(height in m)^2)
* Diabetes pedigree function
* Age (years)

Output Variables (y):

* Class variable (0 or 1)


In [3]:
#
dataset = loadtxt('https://raw.githubusercontent.com/jcharly797/Archivos-/main/iris.csv', delimiter=',')

dataset

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [4.9, 3. , 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.3, 0.2, 1. ],
       [4.6, 3.1, 1.5, 0.2, 1. ],
       [5. , 3.6, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3

In [20]:
# split into input (X) and output (y) variables
X = dataset[:,0:4]
y = dataset[:,4]

## Define Keras Model

Los modelos en Keras se definen como una secuencia de capas.

Creamos un modelo secuencial y agregamos capas una a la vez hasta que estemos satisfechos con nuestra arquitectura de red.

Lo primero que hay que hacer es asegurarse de que la capa de entrada tenga la cantidad correcta de entidades de entrada. Esto se puede especificar al crear la primera capa con el argumento input_shape y configurarlo en (8,) para presentar las ocho variables de entrada como un vector.

### ¿Cómo sabemos el número de capas y sus tipos?

Esta es una pregunta complicada.

Hay heurísticas que puede utilizar y, a menudo, la mejor estructura de red se encuentra mediante un proceso de experimentación de prueba y error.

Generalmente, necesita una red lo suficientemente grande como para capturar la estructura del problema.

En este ejemplo, usemos una estructura de red completamente conectada con tres capas.

Las capas completamente conectadas se definen mediante la clase Dense.

Puede especificar el número de neuronas o nodos en la capa como primer argumento y la función de activación utilizando el argumento de activación.

**Además, utilizaremos la función de activación de unidad lineal rectificada denominada ReLU en las dos primeras capas y la función Sigmoidea en la capa de salida.**

Solía darse el caso de que las funciones de activación Sigmoide y Tanh eran preferidas para todas las capas. Hoy en día, se logra un mejor rendimiento utilizando la función de activación ReLU.

**El uso de un sigmoide en la capa de salida garantiza que la salida de su red esté entre 0 y 1 y es fácil de asignar a una probabilidad de clase 1 o ajustarse a una clasificación estricta de cualquier clase con un umbral predeterminado de 0.5.**

En resumen:

* El modelo espera filas de datos con 8 variables (el argumento input_shape =(8,)).
* La primera capa oculta tiene 12 nodos y utiliza la función de activación ReLU.
* La segunda capa oculta tiene 8 nodos y utiliza la función de activación ReLU.
* La capa de salida tiene un nodo y utiliza la función de activación sigmoide.

In [21]:
#
model = Sequential()

model.add(Dense(12, input_shape = (4,), activation = 'relu'))

model.add(Dense(8, activation = 'relu'))

model.add(Dense(1, activation = 'sigmoid'))

## Compile Keras Model

La compilación del modelo utiliza bibliotecas numéricas eficientes (el llamado backend), como Theano o TensorFlow.

El backend elige automáticamente la mejor manera de representar la red para entrenar y hacer predicciones para ejecutar en su hardware, como CPU, GPU o incluso distribuido.

Al compilar, se debe especificar algunas propiedades adicionales necesarias al entrenar la red. Recuerde entrenar una red significa encontrar el mejor conjunto de ponderaciones para asignar entradas a salidas en su conjunto de datos.

Debe especificar la función de pérdida que se utilizará para evaluar un conjunto de ponderaciones, el optimizador utilizado para buscar diferentes ponderaciones para la red y cualquier métrica opcional que desee recopilar e informar durante el entrenamiento.

En este caso, utilizamos la **entropía cruzada** como argumento de pérdida. Esta pérdida es para problemas de clasificación binaria y se define en Keras como "binary_crossentropy".

Definiremos el optimizador como el eficiente algoritmo de descenso de gradiente estocástico "adam". Esta es una versión popular del descenso de gradiente porque se sintoniza automáticamente y da buenos resultados en una amplia gama de problemas.

Finalmente, debido a que se trata de un problema de clasificación, recopilará e informará la precisión de la clasificación definida mediante el argumento de métricas.

In [22]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Fit Keras Model

Ahora es el momento de ejecutar el modelo con algunos datos.

Entrenamos o ajustamos el modelo a los datos cargados llamando a la función fit() en el modelo.

El entrenamiento se produce a lo largo de épocas (epoch) y cada época se divide en lotes (batches).

* Época: una pasada por todas las filas del conjunto de datos de entrenamiento

* Lote: una o más muestras consideradas por el modelo dentro de una época antes de que se actualicen los pesos.

**Una época comprende uno o más lotes, según el tamaño de lote elegido, y el modelo es apto para muchas épocas.**

El proceso de entrenamiento se ejecutará durante un número fijo de épocas (iteraciones) a través del conjunto de datos que debe especificar mediante el argumento epochs.

Se debe establecer el número de filas del conjunto de datos que se consideran antes de que se actualicen los pesos del modelo dentro de cada época, denominado tamaño de lote, y establecerlo mediante el argumento batch_size.

Nuestro problema se ejecutará durante una pequeña cantidad de épocas (150) y utilizará un tamaño de lote relativamente pequeño de 10.

**Estas configuraciones se pueden elegir experimentalmente mediante prueba y error.**

In [23]:
# fit the keras model on the dataset
model.fit(X, y, epochs=100, batch_size=5)

Epoch 1/100
30/30 [==============================] - 1s 4ms/step - loss: -0.9630 - accuracy: 0.3333
Epoch 2/100
30/30 [==============================] - 0s 4ms/step - loss: -2.6150 - accuracy: 0.3333
Epoch 3/100
30/30 [==============================] - 0s 3ms/step - loss: -4.8775 - accuracy: 0.3333
Epoch 4/100
30/30 [==============================] - 0s 3ms/step - loss: -8.2735 - accuracy: 0.3333
Epoch 5/100
30/30 [==============================] - 0s 4ms/step - loss: -12.8430 - accuracy: 0.3333
Epoch 6/100
30/30 [==============================] - 0s 4ms/step - loss: -18.9086 - accuracy: 0.3333
Epoch 7/100
30/30 [==============================] - 0s 5ms/step - loss: -26.9329 - accuracy: 0.3333
Epoch 8/100
30/30 [==============================] - 0s 3ms/step - loss: -36.9695 - accuracy: 0.3333
Epoch 9/100
30/30 [==============================] - 0s 5ms/step - loss: -49.6794 - accuracy: 0.3333
Epoch 10/100
30/30 [==============================] - 0s 5ms/step - loss: -65.1230 - accuracy: 

## Evaluate Keras Model

Una vez entrenada nuestra red neuronal en todo el conjunto de datos y podemos evaluar el rendimiento de la red en el mismo conjunto de datos.

Esto nos dará una idea de qué tan bien ha modelado el conjunto de datos, pero no da idea de qué tan bien podría funcionar el algoritmo con datos nuevos.

**Esto se hizo por simplicidad, pero lo ideal sería separar los datos en conjuntos de datos de entrenamiento y prueba para entrenar y evaluar su modelo.**

Podemos evaluar el modelo en el conjunto de datos de entrenamiento usando la función evaluate() y pasarle la misma entrada y salida utilizada para entrenar el modelo.

Esto generará una predicción para cada par de entrada y salida y recopilará puntuaciones, incluida la pérdida promedio y cualquier métrica que haya configurado, como la precisión.

La función evaluate() devolverá una lista con dos valores. El primero será la pérdida del modelo en el conjunto de datos y el segundo será la precisión del modelo en el conjunto de datos. Habitualmente sólo interesa informar la precisión, así que podemos ignorar el valor de la pérdida.

In [24]:
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

5/5 [==============================] - 0s 3ms/step - loss: -31684.0273 - accuracy: 0.3333
Accuracy: 33.33


## Nota importante:

Si intenta ejecutar este ejemplo en una computadora portátil IPython o Jupyter, es posible que obtenga un error.

El motivo son las barras de progreso de salida durante el entrenamiento. Puede desactivarlos fácilmente configurando verbose=0 en la llamada a las funciones fit() y evalua(); Por ejemplo:

In [ ]:
# fit the keras model on the dataset without progress bars
model.fit(X, y, epochs=150, batch_size=10, verbose=0)
# evaluate the keras model
_, accuracy = model.evaluate(X, y, verbose=0)

## Make Predictions

In [25]:
# make probability predictions with the model
predictions = model.predict(X)

predictions[:10]

5/5 [==============================] - 0s 3ms/step


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [26]:
# round predictions
rounded = [round(x[0]) for x in predictions]

rounded[:10]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [27]:
# Alternately, you can convert the probability into 0 or 1 to predict crisp classes directly; for example:

# make class predictions with the model
predictions = (model.predict(X) > 0.5).astype(int)

predictions[:10]

5/5 [==============================] - 0s 3ms/step


array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])